/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
//import java.text.SimpleDateFormat;



import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static project.Third_project.jCBclass;
import static project.Third_project.jCBfrom;
import static project.Third_project.jCBto;
import static project.Third_project.jCticket_type;
import static project.Third_project.jDate;
import static project.Third_project.jTtrip_no;
import static project.second_form.jCtraveller_type;
import static project.second_form.jTSSN_traveller;
import static project.second_form.jTfirst;
import static project.second_form.jTlast;
import static project.second_form.jTmid;
import static project.second_form.jTpass_num;
import static project.ticket.jTSSN_ticket;
import static project.ticket.jTclass_ticket;
import static project.ticket.jTdate_ticket;
import static project.ticket.jTfrom_ticket;
import static project.ticket.jTname_ticket;
import static project.ticket.jTpay_type;
import static project.ticket.jTticket_cost;
import static project.ticket.jTticket_type;
import static project.ticket.jTto_ticket;
import static project.ticket.jTtraveller;
import static project.ticket.jTtrip_no_ticket;
import static sun.misc.MessageUtils.where;





/**
 *
 * @author الدولية
 */
public class payment extends javax.swing.JFrame {

    

    

   

    /**
     * Creates new form payment
     */
    public payment() {
        initComponents();
       
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBcost = new javax.swing.JButton();
        jTcost = new javax.swing.JTextField();
        jBsave = new javax.swing.JButton();
        jBclear = new javax.swing.JButton();
        jBBack_tothird = new javax.swing.JButton();
        jBpaydate = new javax.swing.JButton();
        jTpay_date = new javax.swing.JTextField();
        jCpay_type = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setText("payment");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 212, -1));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, -1, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Payment Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 30));

        jBcost.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jBcost.setText("Cost");
        jBcost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBcostMouseClicked(evt);
            }
        });
        jBcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcostActionPerformed(evt);
            }
        });
        getContentPane().add(jBcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, -1));

        jTcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcostActionPerformed(evt);
            }
        });
        getContentPane().add(jTcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 150, 30));

        jBsave.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jBsave.setText("Save");
        jBsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsaveActionPerformed(evt);
            }
        });
        getContentPane().add(jBsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 120, 50));

        jBclear.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jBclear.setText("Clear");
        jBclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclearActionPerformed(evt);
            }
        });
        getContentPane().add(jBclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 120, 50));

        jBBack_tothird.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jBBack_tothird.setText("Back");
        jBBack_tothird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBack_tothirdActionPerformed(evt);
            }
        });
        getContentPane().add(jBBack_tothird, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 110, 50));

        jBpaydate.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jBpaydate.setText("Payment Date");
        jBpaydate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBpaydateMouseClicked(evt);
            }
        });
        jBpaydate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpaydateActionPerformed(evt);
            }
        });
        getContentPane().add(jBpaydate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jTpay_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpay_dateActionPerformed(evt);
            }
        });
        getContentPane().add(jTpay_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 150, 30));

        jCpay_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa" }));
        getContentPane().add(jCpay_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/boosy.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 740, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcostActionPerformed
  //calculate the ticket cost
        if((jCBclass.getSelectedItem().equals("First Class"))&&(jCticket_type.getSelectedItem().equals("One Way"))&&(jCtraveller_type.getSelectedItem().equals("Adult"))){
            jTcost.setText("250");}
      
             else if((jCBclass.getSelectedItem().equals("Standard"))&&(jCticket_type.getSelectedItem().equals("One Way"))&&(jCtraveller_type.getSelectedItem().equals("Adult"))){
               jTcost.setText("550");
              } 
         else if((jCBclass.getSelectedItem().equals("Economy"))&&(jCticket_type.getSelectedItem().equals("One Way"))&&(jCtraveller_type.getSelectedItem().equals("Adult"))){
               jTcost.setText("100");}
         else if((jCBclass.getSelectedItem().equals("First Class"))&&(jCticket_type.getSelectedItem().equals("Round Trip"))&&(jCtraveller_type.getSelectedItem().equals("Adult"))){
            jTcost.setText("500");}
      
             else if((jCBclass.getSelectedItem().equals("Standard"))&&(jCticket_type.getSelectedItem().equals("Round Trip"))&&(jCtraveller_type.getSelectedItem().equals("Adult"))){
               jTcost.setText("300");
              } 
         else if((jCBclass.getSelectedItem().equals("Economy"))&&(jCticket_type.getSelectedItem().equals("Round Trip"))&&(jCtraveller_type.getSelectedItem().equals("Adult"))){
               jTcost.setText("200");}
         else if((jCBclass.getSelectedItem().equals("First Class"))&&(jCticket_type.getSelectedItem().equals("One Way"))&&(jCtraveller_type.getSelectedItem().equals("Adult"))){
            jTcost.setText("125");}
      
             else if((jCBclass.getSelectedItem().equals("Standard"))&&(jCticket_type.getSelectedItem().equals("One Way"))&&(jCtraveller_type.getSelectedItem().equals("Children"))){
               jTcost.setText("75");
              } 
       else if((jCBclass.getSelectedItem().equals("Economy"))&&(jCticket_type.getSelectedItem().equals("One Way"))&&(jCtraveller_type.getSelectedItem().equals("Children"))){
               jTcost.setText("50");}
         else if((jCBclass.getSelectedItem().equals("First Class"))&&(jCticket_type.getSelectedItem().equals("Round Trip"))&&(jCtraveller_type.getSelectedItem().equals("Children"))){
            jTcost.setText("250");}
      
             else if((jCBclass.getSelectedItem().equals("Standard"))&&(jCticket_type.getSelectedItem().equals("Round Trip"))&&(jCtraveller_type.getSelectedItem().equals("Children"))){
               jTcost.setText("150");
              } 
       else if((jCBclass.getSelectedItem().equals("Economy"))&&(jCticket_type.getSelectedItem().equals("Round Trip"))&&(jCtraveller_type.getSelectedItem().equals("Children"))){
               jTcost.setText("100");}
        


    }//GEN-LAST:event_jBcostActionPerformed
    
    private void jBBack_tothirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBack_tothirdActionPerformed
       //to go from the (payment) form to the (third_project) form 
        new Third_project(). setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBBack_tothirdActionPerformed

    private void jBcostMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBcostMouseClicked
        
    }//GEN-LAST:event_jBcostMouseClicked

    private void jBpaydateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpaydateActionPerformed
 // convert the  date that found in (third project) form to string for copying in textfiled that found in the (payment) form
        SimpleDateFormat dFormat=new SimpleDateFormat("yyy-MM-dd");
        String date=dFormat.format(jDate.getDate());
        jTpay_date.setText(date);
    }//GEN-LAST:event_jBpaydateActionPerformed

    private void jBpaydateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBpaydateMouseClicked
//       String nsg= jDate.getToolTipText();
//               jTpay_date.setText(nsg);
    }//GEN-LAST:event_jBpaydateMouseClicked

    private void jTcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcostActionPerformed

    private void jBsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsaveActionPerformed
    //printing data that enterd into the (ticket) form
        new ticket(). setVisible(true);
        this.setVisible(false);
         SimpleDateFormat dFormat=new SimpleDateFormat("yyy-MM-dd");
        String date=dFormat.format(jDate.getDate());
        jTdate_ticket.setText(date);
         jTticket_cost.setText(jTcost.getText());
         jTtrip_no_ticket.setText(jTtrip_no.getText());
        jTSSN_ticket.setText(jTSSN_traveller.getText());
        if((jCtraveller_type.getSelectedItem().equals("Adult"))){
            jTtraveller.setText("Adult");
        }
        if((jCtraveller_type.getSelectedItem().equals("Children"))){
            jTtraveller.setText("Children");}
            if(jCticket_type.getSelectedItem().equals("One Way")){
                jTticket_type.setText("One Way");
            }
            if(jCticket_type.getSelectedItem().equals("Round Trip")){
                 jTticket_type.setText("Round Trip");
            }
         if(jCpay_type.getSelectedItem().equals("Cash")){
               jTpay_type.setText("Cash");
            }
          if(jCpay_type.getSelectedItem().equals("Visa")){
                 jTpay_type.setText("Visa");
            }
          if((jCBclass.getSelectedItem().equals("First Class"))){
             jTclass_ticket.setText("First Class");
          }
         if((jCBclass.getSelectedItem().equals("Standard"))){
              jTclass_ticket.setText("Standard");
         } 
        if ((jCBclass.getSelectedItem().equals("Economy"))){
            jTclass_ticket.setText("Economy");
        }
        jTname_ticket.setText(jTfirst.getText()+" "+jTmid.getText()+" "+jTlast.getText()); 
        String to=(String)jCBto.getSelectedItem();
        jTto_ticket.setText(to);
        String  from=(String)jCBfrom.getSelectedItem();
        jTfrom_ticket.setText(from);
    }//GEN-LAST:event_jBsaveActionPerformed

    private void jBclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclearActionPerformed
      Connection conn = null ;
        PreparedStatement pst = null;
       

        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver loaded");

            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "#Tasneem98");
            System.out.println("Database connected");

           
 pst = conn.prepareStatement("delete from pasport where Number=" + jTpass_num.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

         
             pst = conn.prepareStatement("delete from  traveller_ where ssn=" + jTSSN_traveller.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

            pst.execute();
            pst = conn.prepareStatement("delete from payment where Traveller_SSN=" + jTSSN_traveller.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

            pst.execute();
              pst = conn.prepareStatement("delete from traveller_has_passport where Traveller_SSN=" + jTSSN_traveller.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

            pst.execute();
             pst = conn.prepareStatement("delete from Traveller where SSN=" + jTSSN_traveller.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

            pst.execute();
             pst = conn.prepareStatement("delete from traveller_address where Traveller_SSN=" + jTSSN_traveller.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

            pst.execute();
             pst = conn.prepareStatement("delete from trip where num=" + jTtrip_no.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

            pst.execute();
              pst = conn.prepareStatement("delete from passport where Number=" + jTpass_num.getText());
            
            JOptionPane.showMessageDialog(null, "deleted");

            pst.execute();
            conn.close();

        } catch (HeadlessException | ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

        }



    }//GEN-LAST:event_jBclearActionPerformed

    private void jTpay_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpay_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpay_dateActionPerformed
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBBack_tothird;
    private javax.swing.JButton jBclear;
    private javax.swing.JButton jBcost;
    private javax.swing.JButton jBpaydate;
    private javax.swing.JButton jBsave;
    public static javax.swing.JComboBox<String> jCpay_type;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JTextField jTcost;
    public static javax.swing.JTextField jTpay_date;
    // End of variables declaration//GEN-END:variables

    
}
