/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.KeyEvent;

/**
 *
 * @author الدولية
 */
public class second_form extends javax.swing.JFrame {

    /**
     * Creates new form second_form
     */
    public second_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTaddress = new javax.swing.JTextField();
        jTphone = new javax.swing.JTextField();
        jTSSN_traveller = new javax.swing.JTextField();
        jBnext_tothird = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTfirst = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTmid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTlast = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTnationaliti = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTpass_num = new javax.swing.JTextField();
        jbirthdate = new com.toedter.calendar.JDateChooser();
        jCtraveller_type = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/hhhhh.PNG"))); // NOI18N

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setText("Traveller Information");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 11, 343, 52));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 85, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("SSN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 85, 31));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("Birth Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 85, 31));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setText("Telephone number ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 31));
        getContentPane().add(jTaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 150, 30));

        jTphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTphoneKeyTyped(evt);
            }
        });
        getContentPane().add(jTphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 150, 30));

        jTSSN_traveller.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTSSN_travellerKeyTyped(evt);
            }
        });
        getContentPane().add(jTSSN_traveller, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 150, 30));

        jBnext_tothird.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jBnext_tothird.setText("Next");
        jBnext_tothird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnext_tothirdActionPerformed(evt);
            }
        });
        getContentPane().add(jBnext_tothird, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 105, 48));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText(" First");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 39, -1));

        jTfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfirstActionPerformed(evt);
            }
        });
        jTfirst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTfirstKeyTyped(evt);
            }
        });
        getContentPane().add(jTfirst, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 150, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Mid");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 39, -1));

        jTmid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTmidKeyTyped(evt);
            }
        });
        getContentPane().add(jTmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 150, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setText("Last");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 39, -1));

        jTlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlastActionPerformed(evt);
            }
        });
        jTlast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTlastKeyTyped(evt);
            }
        });
        getContentPane().add(jTlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 150, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel11.setText("Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel14.setText("Traveller");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 90, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("E-mail");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 70, 20));

        jTmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmailActionPerformed(evt);
            }
        });
        getContentPane().add(jTmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 180, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel12.setText("Nationality");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 100, 20));

        jTnationaliti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnationalitiActionPerformed(evt);
            }
        });
        jTnationaliti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTnationalitiKeyTyped(evt);
            }
        });
        getContentPane().add(jTnationaliti, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 160, 180, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel13.setText("Passport Number");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 140, 20));

        jTpass_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpass_numActionPerformed(evt);
            }
        });
        jTpass_num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTpass_numKeyTyped(evt);
            }
        });
        getContentPane().add(jTpass_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 180, 30));
        getContentPane().add(jbirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 150, 30));

        jCtraveller_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Adult", "Children" }));
        getContentPane().add(jCtraveller_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 180, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/w,hfu.PNG"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnext_tothirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnext_tothirdActionPerformed
        //to go (from second_form) form to the (third_project) form  
        new Third_project(). setVisible(true); 
    this.setVisible(false);
    }//GEN-LAST:event_jBnext_tothirdActionPerformed

    private void jTfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfirstActionPerformed
   
    }//GEN-LAST:event_jTfirstActionPerformed

    private void jTmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTmailActionPerformed

    private void jTnationalitiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnationalitiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnationalitiActionPerformed

    private void jTfirstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfirstKeyTyped
      //to writting only characters in the textfiled that its label  is (first )
        char c=evt.getKeyChar(); 
       if(!(Character.isAlphabetic(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            evt.consume();
       }
    }//GEN-LAST:event_jTfirstKeyTyped

    private void jTmidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmidKeyTyped
         //to writting only characters in the textfiled that its label  is (mid )
        char c=evt.getKeyChar(); 
       if(!(Character.isAlphabetic(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            evt.consume();
       }
    }//GEN-LAST:event_jTmidKeyTyped

    private void jTlastKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTlastKeyTyped
      //to writting only characters in the textfiled that its label  is (last )
        char c=evt.getKeyChar(); 
       if(!(Character.isAlphabetic(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            evt.consume();
       }
    }//GEN-LAST:event_jTlastKeyTyped

    private void jTphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTphoneKeyTyped
        //to writting only numbers in the textfiled that its label  is (telephon number )
        char c=evt.getKeyChar(); 
       if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            evt.consume();
       }
    }//GEN-LAST:event_jTphoneKeyTyped

    private void jTpass_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpass_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpass_numActionPerformed

    private void jTpass_numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpass_numKeyTyped
        //to writting only numbers in the textfiled that its label  is (passport number )
        char c=evt.getKeyChar(); 
       if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            evt.consume();
       }
    }//GEN-LAST:event_jTpass_numKeyTyped

    private void jTSSN_travellerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTSSN_travellerKeyTyped
       //to writting only number in the textfiled that its label  is (SSN )
        char c=evt.getKeyChar(); 
       if(!(Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            evt.consume();
       }
    }//GEN-LAST:event_jTSSN_travellerKeyTyped

    private void jTnationalitiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnationalitiKeyTyped
        
        //to writting only characters in the textfiled that its label  is (nationality )
        char c=evt.getKeyChar(); 
       if(!(Character.isAlphabetic(c)||c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE){
            evt.consume();
       }
    }//GEN-LAST:event_jTnationalitiKeyTyped

    private void jTlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlastActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(second_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(second_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(second_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(second_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new second_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnext_tothird;
    public static javax.swing.JComboBox<String> jCtraveller_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jTSSN_traveller;
    public static javax.swing.JTextField jTaddress;
    public static javax.swing.JTextField jTfirst;
    public static javax.swing.JTextField jTlast;
    public static javax.swing.JTextField jTmail;
    public static javax.swing.JTextField jTmid;
    public static javax.swing.JTextField jTnationaliti;
    public static javax.swing.JTextField jTpass_num;
    public static javax.swing.JTextField jTphone;
    public static com.toedter.calendar.JDateChooser jbirthdate;
    // End of variables declaration//GEN-END:variables
}
