/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static project.Third_project.jTtrip_no;
import static project.payment.jTcost;
import static project.payment.jTpay_date;
import static project.second_form.jTSSN_traveller;
import static project.second_form.jTaddress;
import static project.second_form.jTfirst;
import static project.second_form.jTlast;
import static project.second_form.jTmail;
import static project.second_form.jTmid;
import static project.second_form.jTnationaliti;
import static project.second_form.jTpass_num;
import static project.second_form.jTphone;
import static project.second_form.jbirthdate;



/**
 *
 * @author الدولية
 */
public class ticket extends javax.swing.JFrame {

    
   

    /**
     * Creates new form ticket
     */
    public ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTtrip_no_ticket = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTpay_type = new javax.swing.JTextField();
        jTclass_ticket = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTticket_type = new javax.swing.JTextField();
        jTname_ticket = new javax.swing.JTextField();
        jTfrom_ticket = new javax.swing.JTextField();
        jTto_ticket = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTdate_ticket = new javax.swing.JTextField();
        jTticket_cost = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTtraveller = new javax.swing.JTextField();
        jBExit = new javax.swing.JButton();
        jBBack_tothird = new javax.swing.JButton();
        jTSSN_ticket = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 45, 162, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jLabel2.setText("Ticket");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 150, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel14.setText("Traveller");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 80, -1));

        jTtrip_no_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtrip_no_ticketActionPerformed(evt);
            }
        });
        jTtrip_no_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtrip_no_ticketKeyTyped(evt);
            }
        });
        getContentPane().add(jTtrip_no_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 130, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel4.setText("Date");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 40, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setText("Class");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel3.setText("From");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 60, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("To");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setText("Ticket Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 100, -1));

        jTpay_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpay_typeActionPerformed(evt);
            }
        });
        jTpay_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTpay_typeKeyTyped(evt);
            }
        });
        getContentPane().add(jTpay_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 130, 30));

        jTclass_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTclass_ticketActionPerformed(evt);
            }
        });
        jTclass_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTclass_ticketKeyTyped(evt);
            }
        });
        getContentPane().add(jTclass_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 130, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel7.setText("Trip No.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 90, -1));

        jTticket_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTticket_typeActionPerformed(evt);
            }
        });
        jTticket_type.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTticket_typeKeyTyped(evt);
            }
        });
        getContentPane().add(jTticket_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 130, 30));

        jTname_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTname_ticketActionPerformed(evt);
            }
        });
        jTname_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTname_ticketKeyTyped(evt);
            }
        });
        getContentPane().add(jTname_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 30));

        jTfrom_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfrom_ticketActionPerformed(evt);
            }
        });
        jTfrom_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTfrom_ticketKeyTyped(evt);
            }
        });
        getContentPane().add(jTfrom_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 130, 30));

        jTto_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTto_ticketActionPerformed(evt);
            }
        });
        jTto_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTto_ticketKeyTyped(evt);
            }
        });
        getContentPane().add(jTto_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 130, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel9.setText("Payment Type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 120, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel10.setText("Cost");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 70, -1));

        jTdate_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdate_ticketActionPerformed(evt);
            }
        });
        jTdate_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTdate_ticketKeyTyped(evt);
            }
        });
        getContentPane().add(jTdate_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 130, 30));

        jTticket_cost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTticket_costActionPerformed(evt);
            }
        });
        jTticket_cost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTticket_costKeyTyped(evt);
            }
        });
        getContentPane().add(jTticket_cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 130, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel11.setText("Name");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 60, -1));

        jTtraveller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtravellerActionPerformed(evt);
            }
        });
        jTtraveller.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTtravellerKeyTyped(evt);
            }
        });
        getContentPane().add(jTtraveller, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, 30));

        jBExit.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jBExit.setText("Exit");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        getContentPane().add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 80, 40));

        jBBack_tothird.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jBBack_tothird.setText("Back");
        jBBack_tothird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBack_tothirdActionPerformed(evt);
            }
        });
        getContentPane().add(jBBack_tothird, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 90, 40));

        jTSSN_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSSN_ticketActionPerformed(evt);
            }
        });
        jTSSN_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTSSN_ticketKeyTyped(evt);
            }
        });
        getContentPane().add(jTSSN_ticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 130, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel12.setText("SSN");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 60, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jButton1.setText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Captureticket.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 900, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTtrip_no_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtrip_no_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtrip_no_ticketActionPerformed

    private void jTtrip_no_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtrip_no_ticketKeyTyped
        
    }//GEN-LAST:event_jTtrip_no_ticketKeyTyped

    private void jTpay_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpay_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpay_typeActionPerformed

    private void jTpay_typeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpay_typeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpay_typeKeyTyped

    private void jTclass_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTclass_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTclass_ticketActionPerformed

    private void jTclass_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTclass_ticketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTclass_ticketKeyTyped

    private void jTticket_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTticket_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTticket_typeActionPerformed

    private void jTticket_typeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTticket_typeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTticket_typeKeyTyped

    private void jTname_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTname_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTname_ticketActionPerformed

    private void jTname_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTname_ticketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTname_ticketKeyTyped

    private void jTfrom_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfrom_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfrom_ticketActionPerformed

    private void jTfrom_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfrom_ticketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfrom_ticketKeyTyped

    private void jTto_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTto_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTto_ticketActionPerformed

    private void jTto_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTto_ticketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTto_ticketKeyTyped

    private void jTdate_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdate_ticketActionPerformed
       
    }//GEN-LAST:event_jTdate_ticketActionPerformed

    private void jTdate_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdate_ticketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdate_ticketKeyTyped

    private void jTticket_costActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTticket_costActionPerformed
       
    }//GEN-LAST:event_jTticket_costActionPerformed

    private void jTticket_costKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTticket_costKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTticket_costKeyTyped

    private void jTtravellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtravellerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtravellerActionPerformed

    private void jTtravellerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtravellerKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtravellerKeyTyped

    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
        //to exit
        this.dispose();
    }//GEN-LAST:event_jBExitActionPerformed

    private void jBBack_tothirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBack_tothirdActionPerformed
       //to go from the (ticket) form to the (payment) form 
        new payment(). setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBBack_tothirdActionPerformed

    private void jTSSN_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSSN_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSSN_ticketActionPerformed

    private void jTSSN_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTSSN_ticketKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSSN_ticketKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Connection conn=null;
   PreparedStatement pst1 = null;
       
        try {

            Class.forName("com.mysql.jdbc.Driver");
            

           conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "#Tasneem98");
           //insert data into table tha its  name is (Passport)
pst1 = (PreparedStatement) conn.prepareStatement("insert into passport(Number) values(?)");
   pst1.setString(1, jTpass_num.getText());
 pst1.executeUpdate();
 //insert data into table tha its  name is( Payment )
 
  pst1 = (PreparedStatement) conn.prepareStatement("insert into payment_ (cost,payment_Type,payment_Date) values(?,?,?)");
   pst1.setString(1, jTcost.getText());
 pst1.setString(2, jTpay_type.getText());
pst1.setString(3,jTpay_date.getText());

pst1.executeUpdate();
//insert data into table tha its  name is( Traveller)
 pst1 = (PreparedStatement) conn.prepareStatement("insert into traveller_(ssn,first_name,mid_name,last_name,birth_date,phone,email ) values(?,?,?,?,?,?,?)");
   pst1.setString(1, jTSSN_traveller.getText());
 pst1.setString(2, jTfirst.getText());
pst1.setString(3,jTmid.getText());
pst1.setString(4, jTlast.getText());
SimpleDateFormat dFormat=new SimpleDateFormat("yyy-MM-dd");
 String date=dFormat.format(jbirthdate.getDate());
pst1.setString(5, date);
pst1.setString(6,jTphone.getText());
pst1.setString(7, jTmail.getText());

pst1.executeUpdate();
//insert data into table tha its  name is (Traveller_Address )
pst1 = (PreparedStatement) conn.prepareStatement("insert into traveller_address_ (adress) values(?)");
   pst1.setString(1, jTaddress.getText());

 pst1.executeUpdate();
 //insert data into table tha its  name is (Traveller_HAS_Passport)
pst1 = (PreparedStatement) conn.prepareStatement("insert into traveller_has_passport_(nationality) values(?)");
   pst1.setString(1, jTnationaliti.getText());

pst1.executeUpdate();
//insert data into table tha its  name is (Trip)
                      pst1 = (PreparedStatement) conn.prepareStatement("insert into trip(num,From_Country,To_Country,Class,Trip_Type,Date_Go,Date_Back ) values(?,?,?,?,?,?,?)");
           
            pst1.setString(1, jTtrip_no.getText());
pst1.setString(2, jTfrom_ticket.getText());
pst1.setString(3,jTto_ticket.getText());
pst1.setString(4, jTclass_ticket.getText());
pst1.setString(5, jTticket_type.getText());
pst1.setString(6,jTdate_ticket.getText());
pst1.setString(7, jTdate_ticket.getText());
pst1.executeUpdate();



//String query = "update passport set Number=? "
//                    + " where SSN=? ";
//            pst1 = (PreparedStatement) conn.prepareStatement(query);
//             pst1.setString(1, jTpass_num.getText());
//         pst1.execute();
//           query = "update payment set SSN=?,First_Name=?,Mid_Name=?,Last_Name=?,Birth_Day=?,Phone=?,Email=?,Trip_num=? " where SSN=? ";
// 
//            pst1 = (PreparedStatement) conn.prepareStatement(query);
//          pst1.setString(1, jTcost.getText());
// pst1.setString(2, jTpay_type.getText());
//pst1.setString(3,jTpay_date.getText());
//pst1.setString(4, jTSSN_traveller.getText());
//pst1.setString(5,jTtrip_no.getText());
//pst1.setString(6,jTpass_num.getText());

/*String s = اسم المكان اللي هتكتبي فه رقم البطاقه .getText();
            int ssn = Integer.parseInt(s);
            pst.setInt(9, ssn);*/
//pst1.execute();}
//  String query = "update passport set Number=? "
//                    + " where SSN=? ";
//            pst1 = (PreparedStatement) conn.prepareStatement(query);
//
//pst1 = (PreparedStatement) conn.prepareStatement("insert into traveller(SSN,First_Name,Mid_Name,Last_Name,Birth_Day,Phone,Email,Trip_num ) values(?,?,?,?,?,?,?,?)");
//   pst1.setString(1, jTSSN_traveller.getText());
// pst1.setString(2, jTfirst.getText());
//pst1.setString(3,jTmid.getText());
//pst1.setString(4, jTlast.getText());
//SimpleDateFormat dFormat=new SimpleDateFormat("yyy-MM-dd");
// String date=dFormat.format(jbirthdate.getDate());
//pst1.setString(5, date);
//pst1.setString(6,jTphone.getText());
//pst1.setString(7, jTphone.getText());
//pst1.setString(8,jTtrip_no .getText());
 
        



 

        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBack_tothird;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jTSSN_ticket;
    public static javax.swing.JTextField jTclass_ticket;
    public static javax.swing.JTextField jTdate_ticket;
    public static javax.swing.JTextField jTfrom_ticket;
    public static javax.swing.JTextField jTname_ticket;
    public static javax.swing.JTextField jTpay_type;
    public static javax.swing.JTextField jTticket_cost;
    public static javax.swing.JTextField jTticket_type;
    public static javax.swing.JTextField jTto_ticket;
    public static javax.swing.JTextField jTtraveller;
    public static javax.swing.JTextField jTtrip_no_ticket;
    // End of variables declaration//GEN-END:variables
}
